spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: board

  datasource:
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf8
    username: root
    password: lly2018*
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 9096

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/

logging.level.org.springframework.security: DEBUG

logging.leve.org.springframework: DEBUG

feign.hystirx.enable: true

security:
  oauth2:
    resource:
      id: orderserver
      user-info-uri: http://localhost:9099/auth/user
      prefer-token-info: false

management.security.enabled: false